# Generated by Django 4.1.4 on 2023-01-12 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('UserName', models.CharField(max_length=50)),
                ('UserEmail', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('UserName', models.CharField(max_length=50)),
                ('UserEmail', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Left', models.CharField(max_length=50)),
                ('Right', models.CharField(max_length=50)),
                ('Operator', models.CharField(max_length=50)),
                ('Complete', models.BooleanField(default=False)),
                ('Student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentMasterApp.student')),
            ],
        ),
    ]
